apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-01T18:15:10Z"
  generation: 1
  labels:
    app: restrictednginx
  name: restrictednginx
  namespace: lab4
  resourceVersion: "25798"
  uid: 73992f98-5050-42d7-887c-a29f2eab0f43
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: restrictednginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: restrictednginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 125m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-11-01T18:15:10Z"
    lastUpdateTime: "2023-11-01T18:15:10Z"
    message: Created new replica set "restrictednginx-5cd867d5bb"
    reason: NewReplicaSetCreated
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-11-01T18:15:10Z"
    lastUpdateTime: "2023-11-01T18:15:10Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-11-01T18:15:10Z"
    lastUpdateTime: "2023-11-01T18:15:10Z"
    message: 'pods "restrictednginx-5cd867d5bb-lbqtq" is forbidden: failed quota:
      my-quota: must specify cpu for: nginx; memory for: nginx'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 1
  unavailableReplicas: 3
